### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by TheNamlessGuy** [TheNamlessGuy/TheNamlessGuy.github.io#2]
* Rants:
    - [x] The decline of soulslikes
    - [ ] The decline of Bethesda games
    - [ ] There are no good programming languages
    - [ ] My ideal programming language
* Picross
    - [ ] Solve function
    - [ ] Save function - hashing?
* Fallout radio
    - [ ] See code
* YouTube player
    - [ ] Save and load custom playlist options
    - [ ] List video information below player
    - [ ] Make the list and video halves more distinct visually
    - [ ] Specify range and/or list of IDs to loop through
         * Should be able to specify something like "1, 3-5, 8, 8, 6, 3, 1-9"
    - [ ] Shuffle
    - [ ] Filter list based on title and/or tag search
        * Tag search should probably only work on predefined playlists
* Jigsaw
    - [x] Allow snapping of pieces together outside of the solve area
    - [x] Being able to move said snapped together pieces as a group
    - [ ] Round the piece connecty bits
        * Maybe Render the "whole" piece and the mask out the puzzle bits, instead of current approach?
    - [ ] (Optional) better initial puzzle piece placement (ensure no overlap as far as possible)
    - [ ] "Back" button to change config (with warning of "this puzzle will be unrecoverable")
    - [ ] "Show full image" or something
* Hamiltonian Path/Alcazar/whatever generator
    - [ ] Alpha version
    - [ ] Solver?
